
-- TODO : if problem with autogenerated columns,
-- try with a sequence (see https://stackoverflow.com/questions/36244641/h2-equivalent-of-postgres-serial-or-bigserial-column)

CREATE TABLE movie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) UNIQUE NOT NULL,
    duration VARCHAR(10) NOT NULL
    -- note : the INTERVAL HOUR TO MINUTE native h2 format
    -- is simply not supported and I give up on configuring
    -- which converter in what conversion service.
    -- VARCHAR is just fine for my purposes.
);

CREATE TABLE movie_session(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id INTEGER NOT NULL,
    theater VARCHAR(50) NOT NULL,
    day_name VARCHAR(10) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    foreign key (movie_id) references movie(id) on delete cascade
    -- note : cinema is a varchar here but in java
    -- it will be an enum, I hope r2dbc driver can handle
    -- the conversion
);

CREATE TABLE other_activity(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_name VARCHAR(10) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(250) NOT NULL,
    constraint time_integrity check (end_time > start_time)
);